version: '2'
services:
    ninjaccount-app:
        image: ninjaccount
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ninjaccount-postgresql:5432/ninjaccount
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ninjaccount-postgresql:
        extends:
            file: postgresql.yml
            service: ninjaccount-postgresql
