spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource        
        url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: ${POSTGRESQL_ADDON_USER}
        password: ${POSTGRESQL_ADDON_PASSWORD}
        hikari:
            maximumPoolSize: 2
    mail:
        username: ${MAILGUN_LOGIN}
        password: ${MAILGUN_PASSWORD}

jhipster:
    mail:
        from: ${MAILGUN_MAIL_FROM}
        base-url: ${BASE_URL}

application:
    paypal:
        client-id: ${PAYPAL_CLIENT_ID}
        client-secret: ${PAYPAL_CLIENT_SECRET}
        mode: ${PAYPAL_CLIENT_MODE}
    base:
        url: ${BASE_URL}
    srp:
        N: ${N}
        g: ${g}
        k: ${k}

security:
    authentication:
        jwt:
            # This token must be encoded using Base64 (you can type `echo 'secret-key'|base64` on your command line)
            # As this is the PRODUCTION configuration, you MUST change the default key, and store it securely:
            # - In the JHipster Registry (which includes a Spring Cloud Config server)
            # - In a separate `application-prod.yml` file, in the same folder as your executable WAR file
            # - In the `JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET` environment variable
            base64-secret: ${JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET}
